name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install composer and dependencies
        uses: php-actions/composer@v6
        with:
          php_version: "8.3"
#          php_extensions: pdo_mysql ctype dom iconv intl

      - name: PHPUnit Tests
        uses: php-actions/phpunit@v4
        env:
          XDEBUG_MODE: coverage
        with:
#          version: 11
          php_version: "8.3"
          php_extensions: "xdebug"
          configuration: phpunit.xml.dist
#          args: tests --coverage-clover ./coverage.xml

#      - name: PHPStan
#      - uses: php-actions/phpstan@v3
#        with:
#          path: src/
